---
title: "Analysis"
author: Mutong Zhang
date: "2/1/21"
output: html_document
---

<!--- Begin styling code. --->
<style type="text/css">
/* Whole document: */
body{
  font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif;
  font-size: 12pt;
}
h1.title {
  font-size: 38px;
  text-align: center;
}
h4.author {
  font-size: 18px;
  text-align: center;
}
h4.date {
  font-size: 18px;
  text-align: center;
}
</style>
<!--- End styling code. --->

```{r, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Tutorial for \code{my_rf_cv}

The code below predict \code{body_mass_g} using covariates \code{bill_length_mm}, \code{bill_depth_mm}, and \code{flipper_length_mm}.

```{r}
my_penguins <- read.csv("C:/Users/mandy/OneDrive/Stats302/projects/project3_2/part2/Data/my_penguins.csv")
source("C:/Users/mandy/OneDrive/Stats302/projects/project3_2/part2/R/my_rf_cv.R")
rf <- vector()
result <- data.frame()
for (k in c(2, 5, 10)) {
  for (i in 1:30) {
    result[num * 30 + i, 1] <- k
    result[num * 30 + i, 2] <- my_rf_cv(k)
  }
  num <- num + 1
}
colnames(result) <- c("k", "cv_err")
figure <- ggplot(result, aes(x = k, y = cv_err, group = k)) + 
  geom_boxplot() +
  labs(title = "CV estimated MSE with k = 2, 5, 10", x = "number of folds (k)", y = "CV estimated MSE")
avg <- c(mean(result[1:30, 2]), mean(result[31:60, 2]), mean(result[61:90, 2]))
sd <- c(sd(result[1:30, 2]), sd(result[31:60, 2]), sd(result[61:90, 2]))
table <- cbind(avg, sd)
colnames(table) <- c("mean", "standard deviation")
rownames(table) <- c("k = 2", "k = 5", "k = 10")
ggsave(figure1, figure, path = "C:/Users/mandy/OneDrive/Stats302/projects/project3_2/part2/Output/Figures")
result_tidy <- cbind(result[1:30, 2], result[31:60, 2], result[61:90, 2])
colnames(result_tidy) <- c("k = 2", "k = 5", "k = 10")
saveRDS(result_tidy, file = "C:/Users/mandy/OneDrive/Stats302/projects/project3_2/part2/Output/Results")
write_csv(table, file = "C:/Users/mandy/OneDrive/Stats302/projects/project3_2/part2/Output/Results")
```

